name = "ai-dermatics"
uid = "d62d3b23-3b9f-bf3b-5810-4d02b7756bd0868ffc63"
type = "theme"

[[blocks]]
name = "AI Dermatics Embed"
type = "app-embed"
file = "blocks/app-embed.liquid"

[[blocks]]
name = "AI Header Icon (Header)"
type = "header-icon"
file = "blocks/ai-header-icon-block.liquid"

